name: Pipeline examen

on:
  push:
    branches:
      - frabarser1
  workflow_dispatch: #manualmente
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Contruir y Ejecutar los test
        run: |
          chmod +x gradlew 
          ./gradlew build
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Ejecutando los test
        run: |
          chmod +x gradlew        
          ./gradlew test
      - run: echo "${{ github.actor }}"
  Publish:
    runs-on: ubuntu-latest
    needs: Test
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.TOKEN }}
      GITHUB_OAUTH: ${{ secrets.TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Publicando el artefacto
        run: |
          chmod +x gradlew        
          ./gradlew publish
      - run: echo '${{ github.actor }}'